### ISSUE TITLE
Using on phone without SMS plan

### ISSUE THREAD

**Issue by mikeman400** [michaelkourlas/voipms-sms-client#100]
I read Issue #49 and was wondering if the code you tested allowed your app to be set as the default sms app even though it cant send or recieve actual sms messages. 

This would be perfect for me because my phone is on a data only plan which doesn't include sms anyhow. I can't send or recieve sms messages from the network.  

Maybe you don't want to peruse this but I was wondering if you got it to work. 

Thanks for the great app either way.

**Comment by nathanbegin** [comment]
It might be nice to review the compatibility of the app with Android Wear.. because I am not able to answer my sms from my Android Wear smartwatch ...

Nathan

**Comment by michaelkourlas** [comment]
I'm not going to do something like this because the app would essentially be lying to Android about its capabilities. That might be a violation of the Google Play developer agreement. You also wouldn't be notified about any texts you received, including potentially important ones from your wireless carrier about your account.
