### ISSUE TITLE
Frequent, repeated 'synchronizing with VoIP.ms' notifications on Android

### ISSUE THREAD

**Issue by LinearDynamics** [michaelkourlas/voipms-sms-client#159]
https://imgur.com/wPsvRHy
Please let me know what other info I can provide. Thanks.

**Comment by michaelkourlas** [comment]
This is intended behaviour.

The syncing notification has been added to ensure that Android treats the service that retrieves messages from VoIP.ms as a foreground service.

This is necessary to ensure that Android does not kill the service prematurely. Otherwise you might not receive notifications when you receive a new message. 

It might be possible to add an option to hide the notification when the app is itself running in the foreground, or to make the icon transparent when it is not. I'll look into the possibility.

**Comment by michaelkourlas** [comment]
In addition, simply lowering the importance of the notification is not an option. As of Android O, if a foreground service tries to use a minimum importance notification, Android will display a system notification at a higher importance level informing the user that the app is using battery. 

https://stackoverflow.com/questions/45485460/is-it-possible-to-put-a-foreground-service-notification-in-a-notification-channe

**Comment by michaelkuzmin** [comment]
Sorry, didn't see this thread for some reason. Hm I wonder why I wasn't noticing this before... something is different.
