### ISSUE TITLE
Notifications stopped after update

### ISSUE THREAD

**Issue by TorstenTiedtke** [michaelkourlas/voipms-sms-client#182]
Thanks for this app Michael!
I've been using this application for several years without issue.
The last update appears to have broken notifications.
The message still arrives, but there is no notification sound, icon, or vibration.  The only way to see if a message has arrived is by opening the app.
Running on Xiaomi Mi A1 (Android One phone)
Android version: 9 (Patch March 5/2019).
Let me know if there is any additional information you need, or if there is something you'd like me to try.
-Torsten

**Comment by michaelkourlas** [comment]
Funnily enough, I got a Crashlytics report about a Mi A1 running Android 9 that was crashing when trying to send a notification.

> Fatal Exception: java.lang.SecurityException
> UID 10114 does not have permission to content://media/external/audio/media/361 [user 0]
> android.os.Parcel.createException

It looks like you need to give the app the external storage permission so that it can access your ringtone (which is apparently on an SD card). You'll have to do that manually in the Android settings.

This shouldn't be necessary. I can use an SD card ringtone on my LG phone (also running Android 9) without the external storage permission. Maybe Xiaomi devices are more paranoid.

The next update will catch this exception and show a toast if this happens.

**Comment by TorstenTiedtke** [comment]
Thanks Michael - your solution works!!!!
