### ISSUE TITLE
Change Pull to Refresh Behaviour

### ISSUE THREAD

**Issue by bravo90078** [michaelkourlas/voipms-sms-client#19]
Since the app has been updated to only poll for messages since last received on GCM update; I suggest we alter the pull to refresh behavior to behave in the same manner and make the same call; rather than have it be a full overwriting poll. 

A full message sync with the server should probably only be done on first setup/connection, and if manually invoked from the settings menu.

**Comment by fcastilloec** [comment]
I'm not so sure this is such a great idea. Typically you don't have the need to pull for refresh ever. The sync happens everytime you send/receive a message so your message are always on sync (assuming notification are ON). Triggering the pull-to-refresh is just needed when you want a whole sync.
I think it's better to have the user change his/her behavior by not constantly pulling for refresh since the app does it without a problem. So maybe getting completely rid of pull-to-refresh completely would be an alternative, but I think the current behavior is fine the way it is.
It would be great to find out what @michaelkourlas and other users think about this.

**Comment by michaelkourlas** [comment]
I've opted to go with the following approach:
* When the conversation activity loads, when a GCM message is received, and when a message is sent, the app only retrieves messages dated after the most recent message retrieved.
* When the user pulls to refresh, the app starts a synchronization process that is configurable in Settings. The synchronization can:
  * Be limited to recent messages only, per the above.
  * Retrieve deleted messages from VoIP.ms
  * Propagate local deletions to VoIP.ms, and/or
  * Propagate remote deletions from VoIP.ms.

This seems like a good balance, as it allows the user to decide what pull to refresh will do: do a full message sync or only retrieve the latest messages.
