### ISSUE TITLE
No notification

### ISSUE THREAD

**Issue by jgmorris75** [michaelkourlas/voipms-sms-client#198]
Hi. I have notifications turned on (sound and vibrate), but not receiving any.

Moto G4 plus, Android 7.0.

**Comment by michaelkourlas** [comment]
Try:
* using the version from the Google Play Store instead of the F-Droid version
* ensuring the URL callback is set correctly (see Help in the app for details)
* disabling battery optimizations for the app

If none of these work, then it's probably an issue with your device, unfortunately -- notifications work for me.
