### ISSUE TITLE
High latency mode 

### ISSUE THREAD

**Issue by Kawoa** [michaelkourlas/voipms-sms-client#218]
Hello Michael. Very good app clean and fast and low power consumption but i think theres a problem with High latency connections (Satellite 600ms ++ pings) seems like the app is Constantly syncing. Nonestop. When im in town with 30ms connection it works flawlessly. But im experiencing problem with high latency connection. I dint fully understand the code anyway to add a high latency mode in the settings? 

Other then that the app is Very helpful 5stars.

Could be the voip.ms server too. Im not sure. The app actually crashes at one point only on a high latency connection

**Comment by michaelkourlas** [comment]
That doesn't surprise me, but unfortunately there's nothing that can be done about that. We need to synchronize with the VoIP.ms server in order to retrieve SMS messages -- they aren't directly pushed to the app.

(They could be, technically, but that would create unacceptable privacy and security issues -- all your SMS messages would be going through my server!)
