### ISSUE TITLE
Release chat box after send so user can continue typing

### ISSUE THREAD

**Issue by bravo90078** [michaelkourlas/voipms-sms-client#23]
This has been raised before and is probably very much more complicated to implement, but from a purely usability standpoint once the user hits send the message box is locked and the user cannot continue typing until the voip.ms server confirms receipt of the message. 

This process is usually a 2-3 second delay.  If we could uncouple the delivery thread from the locking of the chat box itself it would make the application more responsive.

This like wise also applies when quick responding from the notification widget.

**Comment by fcastilloec** [comment]
Like you mentioned, this is a hard one to implement. The problem is that if we unlock the contents and the message don't get send (bad internet connection, server error, etc) whatever the user typed will be lost. So the user will have to retype everything, locking the message box prevents this from happening, so if there's an error the messages is still present and can be send later without retyping it.

As a case scenario, let's say that we sent a message and we're waiting for a response from the server, meanwhile we have unlock the message box and the user started to type something else. It's very hard to deal with the unsent message and the current typed message. Do we delete the just typed message, to try to send the previous message again? Do we inform the user of the error and just delete the unsent message, making the user retype the whole unsent message?

I think the current behavior is the way to go, unless somebody comes with a better way to deal with it.

**Comment by michaelkourlas** [comment]
This has effectively been fixed due to a significant change in how messages are sent:
* When a message is sent, it is immediately placed into the database with a special delivery-in-progress flag, and it appears in the conversation (though with the text "sending..." instead of the date). 
* Once it is sent, the "sending..." text is replaced with the date. 
* If sending fails for whatever reason, the text is replaced with "not sent. touch to try again." You can then tap the message to try sending it again, or you can just delete it like you would any other message.

As a result of this change, there is no need to lock the send box anymore.

**Comment by fcastilloec** [comment]
These are great news!
