### ISSUE TITLE
Split message ordering

### ISSUE THREAD

**Issue by Whateverman2012** [michaelkourlas/voipms-sms-client#231]
Hi,
  I wonder if the received messages (long enough to be split) have enough precision (ms) to sort them out before showing them.
  Mines are scrambled and it is hard to read since I have to solve the puzzle first.
  Regards

**Comment by michaelkourlas** [comment]
They're already sorted by time and by VoIP.ms ID.

**Comment by JohnMertz** [comment]
@Whateverman2012  I think that an additional note on this would be: if you experience parts of the message being out of order, you should contact VoIP.ms to investigate why the IDs are assigned out of order since it should be their servers that are responsible for splitting the original message. I only use the SMS servuce for bots/automation so I never send or receive messages over 160 chars and don't know if it is a broader issue, but if it is happening to you, it is probably happening to other people and is not the fault of the Android client.

**Comment by yulman19** [comment]
I have this problem too.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
