### ISSUE TITLE
Sign-in failed: VoIP.ms unavailable

### ISSUE THREAD

**Issue by mica** [michaelkourlas/voipms-sms-client#235]
Sometime in the past few days, I've been logged out. I'm getting this error when I try to sign back in:

![Screenshot_20210919-211514](https://user-images.githubusercontent.com/1095254/134067319-57b6a754-c0a9-4856-bc27-15bfdc7fda48.png)

**Comment by michaelkourlas** [comment]
This is an issue with the VoIP.ms API -- you'll have to contact them.

**Comment by JohnMertz** [comment]
For anyone who isn't aware of the situation, voip.ms have been dealing with outages for days, supposedly because of a ransom DDoS attack. You can see [their social media](https://twitter.com/voipms) for news, but they haven't provided much info other than "we're working on it" and putting CloudFlare in front of the website.

The result is that API queries are not returning successful responses because the server is bogged down. Instead of a valid JSON string, requests return errors in HTML:

```
<html>
  <head>
    <title>503 Backend fetch failed</title>
  </head>
  <body>
    <h1>Error 503 Backend fetch failed</h1>
    <p>Backend fetch failed</p>
    <h3>Guru Meditation:</h3>
    <p>XID: 22479611</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

Nothing can be done in the app to fix this.
