### ISSUE TITLE
getMMS API is returning HTML/XML character entity references instead of valid JSON

### ISSUE THREAD

**Issue by yulman19** [michaelkourlas/voipms-sms-client#251]
Letters like this "é" come out as "&eacute" in text messages

**Comment by michaelkourlas** [comment]
I can pretty much guarantee that this is not a problem with the app, which is just handing off standard UTF-8 to the API.

From the VoIP.ms [docs](https://wiki.voip.ms/article/SMS-MMS#Service_Limitations) :

>  We cannot guarantee that accents or special characters including non-Latin letters will be properly delivered.

Are you able to send the same message using the same API call with the accent preserved?

**Comment by michaelkourlas** [comment]
Or are you talking about characters in incoming messages? The app just displays exactly what it gets from the API.

**Comment by baldurmen** [comment]
I have the same issue. Here are two screenshots of the same SMS messages, the first in the webapp (sms.voip.ms) and the second in the app (version v0.6.24, f-droid). This was not an issue in v0.6.23.

Web interface:

![sms_web_interface](https://github.com/michaelkourlas/voipms-sms-client/assets/6070749/ae2c1a29-a1a9-4d6e-907a-66dd297f6b96)

App:

![sms_app_06 24](https://github.com/michaelkourlas/voipms-sms-client/assets/6070749/83b7d0dc-8047-4f92-9bba-9a0f771d0499)

**Comment by baldurmen** [comment]
Probably? Those are HTML entities and maybe the result of the getMMS [message] output is intended to be parsed via some HTML->UTF-8 function? The API doesn't mention anything, but I guess this might be the result of voip.ms interpreting the MIME of the original MMS and re-encoding it to something consistent (since we don't have access to that information via the API).

I did some further tests and I can write messages to someone with non-ascii chars without issues. They are displayed properly in the app and also received properly. So this only seems to affect incoming messages and not outcoming ones.

1. I send `un message avec des accents: é à ô`
2. The contact receives `un message avec des accents: é à ô`
3. They send back `un message avec des accents: é à ô`
4. I get `un message avec des accents: &eacute; &agrave; &ocirc;`

![screenchot](https://github.com/michaelkourlas/voipms-sms-client/assets/6070749/99d0ecb0-7a83-4a7a-9d38-de57972536e9)

**Comment by michaelkourlas** [comment]
I've confirmed the APIs are different. This from getSMS:

```
{"id":"66627691","date":"2023-06-09 21:48:25","type":"1","did":"<redacted>","contact":"<redacted>","message":"\u00c9"}
```

becomes this in `getMMS`:

```
{"id":"66627691","date":"2023-06-0921:48:25","type":"1","did":"<redacted>","contact":"<redacted>","message":"&Eacute;","col_media1":"","col_media2":"","col_media3":"","media":[]}
```

**Comment by michaelkourlas** [comment]
I'm going to leave this open for now and open a ticket.

**Comment by baldurmen** [comment]
I don't know if Voip.MS support replied to your ticket, but it seems that since 2023-06-27 (or at least, that when I saw the change), this problem is not longer happening and I get proper characters instead of those HTML entities.

I guess something changed on their side?

**Comment by michaelkourlas** [comment]
Yes, a rep got back to me and informed me the issue has been fixed.
