### ISSUE TITLE
Sign-in failed: invalid credentials

### ISSUE THREAD

**Issue by bigjdunham** [michaelkourlas/voipms-sms-client#277]
As I try to login (using the VoIP.ms account email and API password) I get a "Sign-in failed: invalid credentials" response. I have reset the API password, and I have tried using my SIP account number rather than the VoIP.ms account email, but nothing of that nature seems to work. I can SMS through the VoIP.ms website (sms.voip.ms) and through SIP applications, but cannot access the account through this app. Any help would be much appreciated. Thanks.

**Comment by bigjdunham** [comment]
Does this app or the voip.ms have a maximum number of characters for the API password? I'm using a pretty long password.

**Comment by JohnMertz** [comment]
I just looked at the source and there does not appear to be a limit on the length of the password field. Presumably VoIP.ms would not let you set an API password that they would not accept.

I suspect that, more than likely, you are probably using your login password (Main Menu->Account Settings->Security->Customer Portal Password) or your SIP password (Main Menu->Account Settings->Security->Main SIP/IAX Password), instead of the API password (Main Menu->SOAP and REST/JSON API->API Password). All three will potentially be different and you would not use the latter to access sms.voip.ms or the SIP application.

**Comment by michaelkourlas** [comment]
I agree with @JohnMertz's advice.
