### ISSUE TITLE
Timezone issues

### ISSUE THREAD

**Issue by LeithJones** [michaelkourlas/voipms-sms-client#35]
If I'm in CST and receive a text from an EST line or send a text to that line, it won't sync between 11pm and 12am CST. Once the day changes the texts all come in. I'm just speculating here, but I think it's because the texts are from tomorrow relative to my device time.

**Comment by michaelkourlas** [comment]
I think I may know what the problem is.

I've always thought that it was bizarre that I had to set the VoIP.ms API's time zone parameter to -1 to retrieve messages timestamped in GMT. The time zone parameter is supposed to be an offset from GMT, so 0 should get me GMT, not -1.

In the course of investigating this bug, I discovered that you can't actually get GMT time from the VoIP.ms API, because all of the timestamps have daylight savings time applied to them, and there's no option to correct for that. Setting the time zone parameter to -1 just seemed to work because I happened to write the relevant code between early March and early November. If I had written it from late November to late February, 0 would have worked and I wouldn't even have realized that something was wrong.

But wait, it gets even better! You can only retrieve messages from the API in 92-day blocks, so you have to specify a start and end date. Now, you would think this date range would correspond to the time zone you specify. Nope! My testing shows that it *always* corresponds to Eastern Daylight Time. For example, even if you received a message on a particular day in a particular GMT offset, and even if you specify that offset in the API request, you'll only see that message in the API results if it was received on the same day in Eastern Daylight Time. The converse (getting messages outside the date range) is also true.

As such, the only safe way to request messages from the API is to provide date ranges in EDT, specify a time zone of -5, and assume the messages will come back in EDT. I can make this fix, but the problem is that the app has been processing and storing message timestamps incorrectly all this time. I'll have to write some special database upgrade code to fix that issue as well.

I'm not sure if this will actually fix your problem - there might be some other issue hiding in the app somewhere - so let me know if you still see this issue in the next release.

**Comment by michaelkourlas** [comment]
I've implemented the fix; reopen if it doesn't work.

**Comment by LeithJones** [comment]
Is there any way you could put the latest apk on git or play? I don't have
the tools to compile it handy.

**Comment by michaelkourlas** [comment]
I'll be uploading the newest release to Google Play soon.
