### ISSUE TITLE
signal integration

### ISSUE THREAD

**Issue by anarcat** [michaelkourlas/voipms-sms-client#55]
Since I use VoIP.ms, I do not have a cell phone carrier contrat. This means the phone device doesn't actually send SMS messages itself, so I use this app to send my text messages. Unfortunately, since there is no way to set this app to send/receive messages as the default app (#49), it means I have to use two completely different apps depending on which contacts I talk with.

Some contacts, for example, use Signal, and it is much better to talk to them using that app, because the communication is encrypted.

What I would like this app to allow, is for other apps to use it as a messaging app. For example, Signal (or Whatsapp, or Telegram, or whatever) could fallback to the VoIP.ms client instead of the builtin carrier SMS system when they do "insecure" text messaging.

I understand this request may overlap with #49 and show my lack of understanding of Android. For that I apologize, but I figured I would try my luck at scratching that specific itch. :)

**Comment by dkisselev** [comment]
Android doesn't really give developers a way to access that part of the subsystem.

Apps can declare themselves as SMS apps, which means that Android will relay messages between the app and the cellphone network subsystem that's built in (so when a message comes in, Android will notify the app with the new message; when you send a message, the app will push the message back to Android, and Android will pass it on to the cellphone networks),

But as you can tell, there's no way to replace that cellphone network component - it's built in to Android, so apps need to integrate with us instead of the other way around. Unfortunately it sounds like Signal has turned down the offer, and I don't think other apps would be willing to put the work in to integrate with a small, highly specific Voip provider.

Technically speaking, it *might* be possible to implement a replacement for the Android SMS subsystem using Xposed framework, which is a system that you install on your phone that allows apps to override the code of other apps (so you could write an XPosed module that overrides the Android SMS system, intercepts messages and feeds them through Voip.ms). But I think writing a module like that might be a pretty big feat (sending SMS is surprisingly complicated, with lots of nuances and edge cases), not many people have Xposed installed, and even fewer use Voip.ms, so it's unlikely there there would be enough interest to make it happen.

**Comment by anarcat** [comment]
Understood, thanks.

**Comment by borfo** [comment]
Posting on this closed issue to point out that it looks like Signal has an API that might allow integration without having to make the Android cell network changes discussed above.

https://github.com/WhisperSystems/Signal-Server/wiki/API-Protocol

**Comment by michaelkourlas** [comment]
Could you clarify how that API would be used to facilitate integration?

**Comment by borfo** [comment]
Sorry - looks like that's an old link.  Current API docs are here: https://www.whispersystems.org/docs/
I haven't looked too closely at it, but it seems that the signal-service API would allow connection to signal servers via the internet (https) rather than by SMS.  I'm not certain whether this would allow connection to Whispersystem's server though - it might require setting up an independent signal server.

**Comment by michaelkourlas** [comment]
So the idea is basically to embed a Signal client into VoIP.ms SMS? Unfortunately that sounds like it would be a great deal of work; I'm not sure there's enough people who would use it to justify it, especially since there's already a bunch of other stuff on my to-do list.

**Comment by borfo** [comment]
Yeah, understood - I just thought I'd point out the existence of the API.  Posted here rather than opening a new thread because I figured this may not be a top-of-the-priority list type of thing.

**Comment by michaelkourlas** [comment]
Thanks for the info -- maybe someone will take the initiative and submit a pull request with the necessary changes.
