### ISSUE TITLE
Collate long messages ( > 160 characters) in conversation

### ISSUE THREAD

**Issue by guiweber** [michaelkourlas/voipms-sms-client#69]
Messages of more than 160 characters are split into separate messages. It would be nice to collate the messages that have been split and make them appear as a single message in the conversation.

**Comment by michaelkourlas** [comment]
I'm not sure there's an easy way to do that, since I think they appear to have been sent at the same time; there's no way to know which message is supposed to come first!

**Comment by guiweber** [comment]
It would be hard to do if Voip.ms doesn't support [concatenated SMS](https://en.wikipedia.org/wiki/Concatenated_SMS). Do you know if they do? If not, they might be open to implement it since most carriers now support this feature.

**Comment by michaelkourlas** [comment]
In general, VoIP.ms seems to be behind the times when it comes to SMS; they only recently started supporting non-ASCII characters in messages. Feel free to ask them to add support!

**Comment by michaelkourlas** [comment]
I'm going to close this for now, though, seeing as there's nothing I can do on the app side.

**Comment by guiweber** [comment]
Ok, I'll send an email to voice.ms and see if I can get something out of them ;- )

**Comment by Philippe-Choquette** [comment]
> I'm not sure there's an easy way to do that, since I think they appear to have been sent at the same time; there's no way to know which message is supposed to come first!
> 

I understand that it would be nearly impossible to fetch messages from the API and detect those that were originally one message, reorder them accordingly and then concatenate them into one.

However, for messages that were sent from your app, it must be possible to keep them as one. After all, I believe it's the app that splits them in order to be passed to the API.

I have only small coding experience, but here's a way I believe it could be done:
- Keep the sent message as one on the GUI
- Only split the message in the background to pass it to the API
- When the split messages are pushed by VoIP.ms towards the app, identity them by running a string "contain" function on existing messages that have the same timeframe.
- Flagged split messages could be deleted before being displayed on the GUI. If this could generate extra processing on upcoming refreshes, a list could be created with the IDs of the split messages so that they get ignored on refreshes.

Of course it's just an idea and I'm aware that would reduce the simplicity of the code. In addition, the possible upcoming support of MMS makes this less justifiable.

**Comment by michaelkourlas** [comment]
There are a couple of problems with that approach:
* there's no way to indicate which IDs are associated with which message subsets
* the message history no longer corresponds with the actual message history on sms.voip.ms
