### ISSUE TITLE
Group texts

### ISSUE THREAD

**Issue by michaelkourlas** [michaelkourlas/voipms-sms-client#74]
I've received a number of requests for a group texting feature.

**Comment by ralphfrost** [comment]
Michael, I appreciate your fine SMS App and the push notification. I am one interested in adding Group Text but the more I read about it recently,  isn't that multiple-addressing feature also a feature requiring MMS rather than SMS?  So, would MMS be part of this enhancement?  That would be nice if doable.   ....I am an old (Foxpro/PHP-MySQL) programmer. If I can help w/ testing, etc., let me know.  ralph@refrost.com

**Comment by michaelkourlas** [comment]
Well, you don't need MMS support just to send a text message to multiple people, but I think real group texting (the ability to maintain a conversation among people people) requires MMS support, yes.

Unfortunately, MMS support for the app is impossible until VoIP.ms itself starts supporting it.

**Comment by michaelkourlas** [comment]
I've decided not to support this, as I don't think there's a good way to do this on the UI side without better support from VoIP.ms.
