### ISSUE TITLE
Messages Received Late

### ISSUE THREAD

**Issue by ailicic** [michaelkourlas/voipms-sms-client#97]
This app works great for the most part. On one phone I rarely have issues but on another phone messages arrive late (10-120 min) even though the sync interval is 1 min and I have set the callback URL in the voip.ms config. Is there a way I can debug this issue and find out what is causing the delay?

I'm using v0.46. If you need more info let me know.

**Comment by michaelkourlas** [comment]
Unfortunately I can't really determine what would be causing the problem here with any degree of certainty. A couple of ideas:
* If you're running a more recent version of Android (such as Marshmellow) it's possible that it's not respecting the 1 minute sync interval and forcing the app to check at less frequent intervals. I don't see why that would prevent FCM notifications, though.
* It's possible VoIP.ms is delaying the callback to my FCM server for some reason. Next time there's a delay you can email me your DID and the date the message was received vs. when it was supposed to be received and I can check my server logs to see when VoIP.ms sent the callback.

Incidentally, if you're using the 1 minute sync just for notifications, you can disable that and just use FCM instead; FCM uses push notifications which should be instantaneous.

**Comment by ailicic** [comment]
It seems to be due to network latency / dropped packets. When I was visiting a nearby large city where cell reception was strong the issue largely disappeared.

Thanks for your work!
